### ISSUE TITLE
Unable to update Typheous due to `grac` dependency

### ISSUE THREAD

**Issue by gadimbaylisahil** [viafintech/Barzahlen-Ruby#10]
Hi, Viafintech team!

Firstly, thanks for building this client which was useful for us over the years.  

We have run into the issue where we can't use up to date version of Typheous, anything over 0.6.9 to be exact, as `grac` has a lock on it.  With older versions of Typheous installation, we run into segmentation faults, which I am trying to debug. But considering it being 7 years old, maybe it's time for an update.

I would go ahead and create a PR, but considering the `grac` gem is also built by you, I am asking this to know how big of an interface change would it be.  

Can we update `grac` to up to date version without much hassle? If so, will you accept the changes?

Thanks

**Comment by gadimbaylisahil** [comment]
I have updated it(~> 4) in a private repo for our own use and we did not have any regressions. 

Specs also pass.

When reading the [changelog](https://github.com/viafintech/grac/blob/master/CHANGELOG.md) of [grac](https://github.com/viafintech/grac), I do not see any major changes except:

`Grac now raises an exception on receiving only a partial response. This can happen when typhoeus times out while not having received the entire response.`

**Comment by tobischo** [comment]
Hi @gadimbaylisahil 

The update should not cause any issues. The partial response handling would otherwise result in an invalid json error, so in that regard, only the exception that was raised is different, but not whether an exception is raised

**Comment by tobischo** [comment]
I published v2.2.0 with updated dependencies now

**Comment by gadimbaylisahil** [comment]
@tobischo appreciated!
